#!/usr/bin/env bash
# Displays Best School for 9 times and 
# displays hi before Best School
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
